'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VacationsRequestsReports
    
    '''<summary>
    '''empsFilterCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents empsFilterCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''fromEmpLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fromEmpLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''fromEmpDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fromEmpDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''toEmpLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents toEmpLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''toEmpDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents toEmpDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''VacationRequestDB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VacationRequestDB As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''datesFilterCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datesFilterCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''fromDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fromDateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''fromDateCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fromDateCalendar As Global.System.Web.UI.WebControls.Calendar
    
    '''<summary>
    '''toDatelabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents toDatelabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''toDateCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents toDateCalendar As Global.System.Web.UI.WebControls.Calendar
    
    '''<summary>
    '''filterButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filterButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''CrystalReportViewer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CrystalReportViewer1 As Global.CrystalDecisions.Web.CrystalReportViewer
End Class
